# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BunnyshellCli < Formula
  desc "Bunnyshell's command line tool to create and manage on-demand environments."
  homepage "https://documentation.bunnyshell.com"
  version "0.23.0"

  on_macos do
    on_intel do
      url "https://github.com/bunnyshell/cli/releases/download/v0.23.0/bns_0.23.0_Darwin_x86_64.tar.gz"
      sha256 "d030a93a36aa5925af41cdbd5d1d7525d642b4c5ca02dbed583551b2eb9fc8db"

      def install
        bin.install "bns"
      end
    end
    on_arm do
      url "https://github.com/bunnyshell/cli/releases/download/v0.23.0/bns_0.23.0_Darwin_arm64.tar.gz"
      sha256 "c31b05e7850516b3dea373daae3490070275a19fdc886dee4f3035558e641325"

      def install
        bin.install "bns"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bunnyshell/cli/releases/download/v0.23.0/bns_0.23.0_Linux_x86_64.tar.gz"
        sha256 "268b08f9e6e193584dc9f1eb7986e541d8ad60a34838079090ee0329c199e871"

        def install
          bin.install "bns"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bunnyshell/cli/releases/download/v0.23.0/bns_0.23.0_Linux_arm64.tar.gz"
        sha256 "05e7e1f71d7705024a1373a7f33931ede739c30d5a7c863eaab89f022bf795b8"

        def install
          bin.install "bns"
        end
      end
    end
  end
end
