# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BunnyshellCli < Formula
  desc "Bunnyshell's command line tool to create and manage on-demand environments."
  homepage "https://documentation.bunnyshell.com"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bunnyshell/cli/releases/download/v0.15.0/bns_0.15.0_Darwin_arm64.tar.gz"
      sha256 "e36c279bee018c18e4036d5765577b24ac598ab4ac08d7c6f4b702ea6068cb80"

      def install
        bin.install "bns"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bunnyshell/cli/releases/download/v0.15.0/bns_0.15.0_Darwin_x86_64.tar.gz"
      sha256 "2a7e2ae4605405f872693c618e3c4cec9183bd71f86c89ce2a164a022659b7ce"

      def install
        bin.install "bns"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bunnyshell/cli/releases/download/v0.15.0/bns_0.15.0_Linux_arm64.tar.gz"
      sha256 "1938f9c5cee5d059a5d10be4aab365c76a0b57657d9b73b7239e4b4ba1b67cc0"

      def install
        bin.install "bns"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bunnyshell/cli/releases/download/v0.15.0/bns_0.15.0_Linux_x86_64.tar.gz"
      sha256 "e172413a66843274c4134a312882da97c6da90962bf7a80ba346dc2ec9f4190c"

      def install
        bin.install "bns"
      end
    end
  end
end
