# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Bunnyshell's command line tool to create and manage on-demand environments."
  homepage "https://documentation.bunnyshell.com"
  version "0.8.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bunnyshellosi/cli/releases/download/v0.8.6/bunnyshell-cli_0.8.6_Darwin_arm64.tar.gz"
      sha256 "a20c493db667c2a08214b41151b0135acb29f1adc49857130d4eba42363df9ff"

      def install
        bin.install "bunnyshell-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bunnyshellosi/cli/releases/download/v0.8.6/bunnyshell-cli_0.8.6_Darwin_x86_64.tar.gz"
      sha256 "dd46f939b54afbd5d6354c029155ec79347781592fc3651d1d40ece74c648db1"

      def install
        bin.install "bunnyshell-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bunnyshellosi/cli/releases/download/v0.8.6/bunnyshell-cli_0.8.6_Linux_arm64.tar.gz"
      sha256 "d38891ec236c1270b5cbad583d62b81a0e4c5dbecd912add78e2508057d31da1"

      def install
        bin.install "bunnyshell-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bunnyshellosi/cli/releases/download/v0.8.6/bunnyshell-cli_0.8.6_Linux_x86_64.tar.gz"
      sha256 "7f8c1b876d85efc9a0bc11ae3eb36e19ea305d72f1cd6442ca70e7ffc1f990a6"

      def install
        bin.install "bunnyshell-cli"
      end
    end
  end
end
